# Generated by Django 5.1.7 on 2025-03-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30)),
                ('lots', models.DecimalField(decimal_places=2, max_digits=3)),
                ('trade_type', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=4)),
                ('take_profit', models.DecimalField(decimal_places=6, max_digits=6)),
                ('stop_loss', models.DecimalField(decimal_places=6, max_digits=6)),
                ('close_price', models.DecimalField(decimal_places=6, max_digits=6)),
                ('open_price', models.DecimalField(decimal_places=6, max_digits=6)),
                ('entry_time', models.DateTimeField()),
                ('close_time', models.DateTimeField()),
            ],
        ),
    ]
