# Generated by Django 5.1.7 on 2025-04-14 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_author_categories_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='categories',
        ),
    ]
